version: '3.6'
services:
  kibana:
    container_name: ddev-${DDEV_SITENAME}-kibana
    hostname: ${DDEV_SITENAME}-kibana
    image: docker.elastic.co/kibana/kibana:7.10.1
    restart: always
    ports:
      - '5601'
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=5601:5601
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
    volumes:
      - '.:/mnt/ddev_config'
  elasticsearch:
    links:
      - kibana:kibana
